backend:
  name: git-gateway
  branch: main  # Change to your branch if different

media_folder: "materials" # Stores uploaded PDFs
public_folder: "/materials"

collections:
  - name: "blogs"
    label: "Blogs"
    folder: "blogs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "materials"
    label: "Study Materials"
    folder: "materials"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Upload PDF", name: "file", widget: "file" }
      - { label: "Description", name: "description", widget: "text" }
